---

base_archiving_tools:
  - file-roller
  - p7zip-full
  - p7zip-rar
  - rar
  - unrar
  - unzip
  - zip

base_productivity_tools:
  - libreoffice
  - foliate
  - qalc
  - copyq

base_system_tools:
  - fatrace
  - fdupes
  - gnome-calculator
  - gufw
  - nala    # alternative package management tool to apt/apt-get
  - progress
  - pwgen
  - syncthing
  - trash-cli  # command line tools to interact with files/directories in rubbish bin
  - smartmontools
  - nvme-cli

base_system_tools_laptop:
  - powertop

base_download_tools:
  - aria2
  - transmission
  - wget
  - yt-dlp
  - grsync

base_developer_tools:
  - alacritty  # OpenGL terminal emulator
  - ansible
  - ansible-lint
  - apostrophe
  - bat
  - fzf
  - ripgrep
  - zoxide
  - ranger
  - tmux
  - tmuxp
  - bpython
  - black
  - btop  # Modern and colorful command line resource monitor that shows usage and stats
  - ca-certificates
  - cargo
  - cloc
  - clusterssh
  - csvkit
  - curl
  - pipx
  - openjdk-17-jre-headless
  - dos2unix
  - duf  # Disk Usage/Free Utility
  - entr
  - expect
  - filezilla
  - fonts-powerline
  - fzf
  - g++
  - gawk
  - geoip-bin
  - git
  - git-delta  # A syntax-highlighting pager for git, diff, and grep output
  - git-extras
  - golang-go
  - htop
  - httpie
  - inotify-tools
  - ipython3
  - jq
  - make
  - meld
  - miller
  - moreutils
  - mssh
  - mtr-tiny
  - ncat
  - nmap
  - nmon
  - nodejs
  - pandoc
  - parallel
  - pcre2-utils  # provides pcre2grep and pcre2test (perl-compatible regex)
  - pssh
  - ptpython
  - pv
  - pylint
  - python3-cachecontrol
  - python3-jmespath
  - python3-pip
  - python3-poetry
  - ranger
  - rclone
  - remmina
  - rename
  - ripgrep  # launch using rg from the cli
  - shellcheck
  - siege
  - socat
  - sshfs
  - sshpass
  - sshuttle
  - stow  # symlink manager
  - tcptraceroute  # traceroute implementation using TCP packets
  - tig
  - tilix  # A tiling terminal emulator for Linux using GTK+ 3
  - tmux
  - tmuxp
  - tree
  - xsel
  - yamllint
  - zeal

base_virtualization_tools:
  - virt-manager
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - bridge-utils
  - dnsmasq-base
  - virtinst
  - ovmf

base_media_tools:
  - ffmpeg
  - gimp
  - imagemagick
  - libimage-exiftool-perl
  - mediainfo
  - soundconverter
  - ubuntu-restricted-extras
  - vlc

golang_tools:
  - github.com/charmbracelet/glow@latest  # Render markdown on the CLI
  - oss.terrastruct.com/d2@latest  # d2 diagram as code tool
  - github.com/jesseduffield/lazygit@latest  # simple terminal UI for git commands
  - github.com/wagoodman/dive@latest  # tool for exploring each layer in a docker image

# base_permanent_night_light:
#   night_light_enabled: false              # set this to true for permanently turning on night light
#   night_light_schedule_automatic: false
#   night_light_schedule_from: 0
#   night_light_schedule_to: 24
#   night_light_temperature: 4200

base_obsidian_download_base_url: "https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest"

...
