---

vscode_repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
vscode_apt_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
vscode_apt_key_keyring: "/etc/apt/trusted.gpg.d/microsoft.gpg"

vscode_extensions:
  - EditorConfig.EditorConfig
  - github.vscode-github-actions
  - ldez.ignore-files
  - eamodio.gitlens
  - golang.Go
  - oderwat.indent-rainbow
  - yzhang.markdown-all-in-one
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-container
  - vscode-icons-team.vscode-icons
  - esbenp.prettier-vscode
  - redhat.vscode-yaml
  - hashicorp.terraform
  - rangav.vscode-thunder-client  # lightweight rest client for testing APIs
  - redhat.ansible  # ansible extension
  - timonwong.shellcheck  # shellcheck linter for sh/bash/dash/ksh scripts

...
